# Configuración limpia para H2
spring.datasource.url=jdbc:h2:mem:motofixdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Forzar a Hibernate a que cree las tablas en H2 según las clases
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true