# Configuración de la conexión a PostgreSQL en Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/motofix
spring.datasource.username=admin
spring.datasource.password=motos123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate / JPA
# update: hace que Spring cree o actualice las tablas automáticamente sin borrar los datos que ya existan
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect